wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.52.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749898493
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      - 24
      4: 3.11.5
      5: 0.17.1
      6: 4.52.2
      8:
      - 3
      - 5
      13: windows-amd64
